### ISSUE TITLE
Goes to Reddit, opens a login popup and dies

### ISSUE THREAD

**Issue by Dingo64** [ecthros/uncaptcha#8]
Perhaps you could help me with this problem. It goes to Reddits, opens a login popup (as you can see on the image below) and then just dies with this message:

```
INFO:root:[*] Starting attack on Reddit's recaptcha
Traceback (most recent call last):
  File "main.py", line 346, in <module>
    main()
  File "main.py", line 285, in main
    fill_out_profile(driver)
  File "main.py", line 252, in fill_out_profile
    type_style(driver, "user_reg", username)
  File "main.py", line 233, in type_like_bot
    driver.find_element(By.ID, element).send_keys(string)
  File "C:\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py",
line 320, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT, {'value': keys_to_typing(value)}
)
  File "C:\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py",
line 461, in _execute
    return self._parent.execute(command, params)
  File "C:\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", l
ine 236, in execute
    self.error_handler.check_response(response)
  File "C:\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py"
, line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d902
3f),platform=Windows NT 6.1.7601 SP1 x86_64)
```

![reddit1](https://user-images.githubusercontent.com/13681463/35199246-e885c8e4-fefb-11e7-8d7c-44a5d950a1b1.png)

**Comment by dpatel19** [comment]
You must ensure that you have the appropriate version of Selenium for the given web browser.
